### PR TITLE
a loader for certain formats & .BIC-files from XXDP

### PR DESCRIPTION
**Pull request by folkertvanheusden**

### CODE REVIEW

**Comment by folkertvanheusden** [comment]
These are especially interesting: https://www.pdp-11.nl/xxdp-list.html#XXDP%2011/70%20CPU

Output looks like e.g.:

```
folkert@oensoens ~/Projects/PDP-11/json/python-pdp11-emulator (tapeload)$ rm pdp11.log ; ./tapeloader.py ../../BIC/EQKCE1.BIC
Start at 000200

^@^@000:00:00
^@^@ERRORPC PHYSC PC    PSW   MAINT   TEST NO SUB-PASS CNT
^@^@064470  00064470  000000  000000  000000  000000  000000
^@^@UNEXPECTED TRAP TO 4
^@^@PCOFTP  PHYSPC    PSW   CPUERR
^@^@005424  00005424  000344  000060
^@^@
^@^@
^@^@000:00:00
^@^@ERRORPC PHYSC PC    PSW   MAINT   TEST NO SUB-PASS CNT
```

**Comment by outofmbufs** [comment]
Where can I find documentation on the .BIC file format? 
And where can I get copies of the binary files you are loading for the diagnostics? At the link you gave I only see high-level descriptions of the tests themselves??

**Comment by folkertvanheusden** [comment]
Hello,

I can't remember where I got it from that .BIC-files are just tape-files. Maybe an other emulator, can't remember which.

I retrieved the disk-images (in rl02 or rk05 format) from bitsavers.org. There's https://github.com/AK6DN/xxdpdir which is a tool retrieve individual .bic-files from the xxdp-set. Note that XXDP contains  menu-software to run each but for automated unit-tested I found it convenient to retrieve them from the set and run them as individual tape-files.
For it to be usable, check http://www.bitsavers.org/pdf/dec/pdp11/microfiche/Diagnostic_Program_Listings/Listings/ where you can find the sourcecode of many of these programs.

**Comment by outofmbufs** [comment]
Support for this is in boot.py now

**Pull request closed without merging**
