### PR TITLE
init telnet session to not do local echo

### PR DESCRIPTION
**Pull request by folkertvanheusden**
That way you can do telnet localhost 1170 without password being echood.

### CODE REVIEW

**Comment by outofmbufs** [comment]
But that's telnet-specific and doesn't work with nc (or anything that isn't telnet).
There's no telnet on my mac (the demise of some of these is old tools is a crying shame but is what it is). I just use netcat (nc) this way:

  % (stty raw; nc localhost 1170; stty sane)

Did I misunderstand your point? I don't think this is a good generic thing to do in the emulation.

**Comment by folkertvanheusden** [comment]
Hi,

It was a convenience thing as I use telnet for these things. But the raw
tty works as well.

**Comment by outofmbufs** [comment]
I will look at making this an option to KL11() (__init__) and the boot.py commands.

While I'm thinking about this the whole "go to another window and connect" thing is silly. On the list is: figure out how to take over stdin/stdout like SIMH does so you can stay in the boot window.

**Comment by outofmbufs** [comment]
See updates to boot.py and kl11.py just pushed. Specify --telnet to boot.py command (or at other appropriate interfaces depending on how you are using all this)

**Comment by folkertvanheusden** [comment]
Thanks!

**Pull request closed without merging**
